---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/houses":
    get:
      summary: list houses
      responses:
        '200':
          description: successful
    post:
      summary: create house
      responses:
        '200':
          description: successful
  "/api/v1/houses/new":
    get:
      summary: new house
      responses:
        '200':
          description: successful
  "/api/v1/houses/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show house
      responses:
        '200':
          description: successful
    patch:
      summary: update house
      responses:
        '200':
          description: successful
    put:
      summary: update house
      responses:
        '200':
          description: successful
    delete:
      summary: delete house
      responses:
        '200':
          description: successful
  "/api/v1/reservations":
    get:
      summary: list reservations
      responses:
        '200':
          description: successful
    post:
      summary: create reservation
      responses:
        '200':
          description: successful
  "/api/v1/reservations/new":
    get:
      summary: new reservation
      responses:
        '200':
          description: successful
  "/api/v1/reservations/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show reservation
      responses:
        '200':
          description: successful
    patch:
      summary: update reservation
      responses:
        '200':
          description: successful
    put:
      summary: update reservation
      responses:
        '200':
          description: successful
    delete:
      summary: delete reservation
      responses:
        '200':
          description: successful
  "/api/v1/users":
    get:
      summary: list users
      responses:
        '200':
          description: successful
  "/api/v1/users/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show user
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
